version: '3'
services:

  obisyslog: # Docker container name
    build:
      context: /home/home/obihai # Folder name where you have cloned files
      dockerfile: dockerfile # Docker build file, no change needed, must be under above listed folder
    image: obisyslog
    container_name: obisyslog # Docker container name
    network_mode: "host"
    volumes:
      - /home/home/obihai:/config # Folder name where you have config file
      - /etc/localtime:/etc/localtime:ro # Time sync to host machine
    restart: unless-stopped  # Restart policy
